# Generated by Django 3.2.19 on 2023-05-28 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre')),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)], verbose_name='Año')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999999999.0)], verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Modelo de Auto',
                'verbose_name_plural': 'Modelos de Autos',
                'ordering': ['nombre', 'anio'],
            },
        ),
    ]
